### ISSUE TITLE
Image/video share

### ISSUE THREAD

**Issue by zlguo1996** [JitsiPartyTeam/jitsi-party#12]
## Objective
Share images/videos by URL.
Upload and hosting should be not in our host but use other services.

## Todos
The implementation contains following parts:
1. Add store for storing urls and their properties.
2. Add UI for adding and showing share contents.
3. Add API to sync with remote participants.
#### 1 - Store
Add an store (`SharedContents`) for storing all urls and properties (`SharedContent`).
- `SharedContents`: a map about `SharedContent`, the key is unique id.
- `SharedContent`: stores url, position, size / scale, author...
In local participant store, add a property: `shared`.
- `shared`: a set of unique id of `SharedContent` authored by this participant.
- When the participant leave conference, do something (?) with shared content. 
#### 2 - UI
- In Map - ShareLayer, add code to show shared content from store. Some shared content should be edittable (position, size / scale) by user.
- Add a dialog to accept url, and add the it to store. 
#### 3 - Sync with remote
- API observe and alter store, communicate with remote participants.

**Comment by zlguo1996** [comment]
Authority is worth discussion in this problem:
- After share created, users can change its properties (position, scale, delete)?
- Only author could change its properties?
- What about author leaved conference?
@hasevr

**Comment by hasevr** [comment]
I think what we should use will be server less database such as Cloud Firestore. 
Conference should be created with email address and by admins who have access to the email address manage the conference room.
The setting of the conference room will decide what users can do.
In one of the settings, users will be assigned some amount of area on the map. User can update and manage what they upload on the map.  Users who want to upload on the map will also asked to give email if they want to keep the uploaded objects. Otherwise they will deleted when the user is disconnected.

**Comment by hasevr** [comment]
Some people try to use github as data storage. It may work but I think server less DB is better.

**Comment by hasevr** [comment]
May be the option will be
1. Use ordinal database which requires sever settings.
2. Use cloud database which requires use login.
3. Use local file or browser storage of each participants and sync by jitsi server.
I think 3 is the best. No extra server is needed. Everyone who joint the conference can copy or restore the room.

**Comment by hasevr** [comment]
By sendCommand of libJitsiMeet, we will be able to implement 3.

**Comment by zlguo1996** [comment]
This feature have been implemented. Close this issue.
